name: Pull from GitHub

on:
  push:
    branches:
      - main # 可以根据你的主分支名称来修改

jobs:
  pull:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: SSH into GCP Instance
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.GCP_HOST }}
          username: ${{ secrets.GCP_USERNAME }}
          password: ${{ secrets.GCP_PASSWORD }}
          script: |
            cd /path/to/your/project
            git pull origin main # 或者你想要的分支
