name: Pull from GCP

on:
  push:
    branches:
      - main # 或者你使用的主分支名

jobs:
  pull:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up SSH key
        run: echo "$GCP_SSH_KEY" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa

      - name: SSH into GCP Instance
        run: |
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null your_username@your_instance_ip 'cd /path/to/your/project && git pull origin main' # 或者你想要的分支
